/* Generated by mkromfs. Edit with caution. */
#include <rtthread.h>
#include <dfs_romfs.h>



static const rt_uint8_t _romfs_root_readme_txt[] = {
0x68,0x65,0x6c,0x6c,0x6f
};

static const struct romfs_dirent _romfs_root[] = {
    {ROMFS_DIRENT_DIR, "hello", RT_NULL, 0},
    {ROMFS_DIRENT_FILE, "readme.txt", (rt_uint8_t *)_romfs_root_readme_txt, sizeof(_romfs_root_readme_txt)/sizeof(_romfs_root_readme_txt[0])}
};

const struct romfs_dirent romfs_root = {
    ROMFS_DIRENT_DIR, "/", (rt_uint8_t *)_romfs_root, sizeof(_romfs_root)/sizeof(_romfs_root[0])
};
